os: osx
language: node_js
node_js:
  - "8.6.0"
env: 
  - NODE_RUNTIME=node TARGET=8.6.0
  - NODE_RUNTIME=electron TARGET=2.0.0 DIST_URL=https://atom.io/download/atom-shell
install:
  - yarn
  - yarn global add node-pre-gyp node-pre-gyp-github aws-sdk
  - node-pre-gyp configure --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - node-pre-gyp build --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - node-pre-gyp package --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - ls -lah build/Release
  - ls -lah build
  - node-pre-gyp-github publish --release
