os: osx
osx_image: xcode10
language: node_js
node_js:
  - "8"
after_success:
  - yarn global add node-pre-gyp-github aws-sdk;
    node-pre-gyp-github package;
    node-pre-gyp-github publish --release;
